development:
  did_contract:
    address: 0x07356Cc7c5641B24e22BCF1DBB77E9D7eaf44F68
    net: infuraRopsten
  logger:
    logName: 2vid
    logLevel: "DEBUG"
  DESTINATION: url
  mysql:
    username: "root"
    password: ""
    host: localhost
    port: 3306
    dbname: 2vid_test
  redis:
    url: localhost:6379
    password: ""

production:
  did_contract: 
    address: 0x07356Cc7c5641B24e22BCF1DBB77E9D7eaf44F68
    net: infuraRopsten
  logger:
    logName: 2vid
    logLevel: "DEBUG"
  DESTINATION: url
  mysql:
    username: 
    password: 
    host: 
    port: 
    dbname:
  redis:
    url: 
    password: 

environment: development